-- Optional seed data for local validation after schema reset.
-- Password hashes should be generated by backend logic; this file is intentionally minimal.

-- Add application-level users via /api/auth/signup where possible.
-- For production-like reset flow, allow Backend init_db() to create baseline records.
